# This is a basic workflow to help you get started with Actions

name: CI Develop

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [develop, master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['12']
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm install
      # - name: Cache npm
      #   uses: actions/cache@v2
      #   env:
      #     cache-name: npm
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-cache-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: ${{ runner.os }}-cache-${{ env.cache-name }}-

  lint:
    needs: install
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['12']
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Run eslint
        run: npm run lint

  test:
    needs: install
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['12']
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Run test
        run: npm run test

  build:
    needs: install
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['12']
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Run build
        run: npm run build
